# Generated by Django 3.2 on 2021-05-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalorder',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='status',
            field=models.CharField(choices=[('0', '待出貨'), ('1', '待收貨'), ('2', '已完成'), ('3', '已取消')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='update_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
