# Generated by Django 3.2 on 2021-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210524_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '購物車明細', 'verbose_name_plural': '購物車明細'},
        ),
        migrations.AlterModelOptions(
            name='totalorder',
            options={'verbose_name': '訂單明細', 'verbose_name_plural': '訂單明細'},
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
